### ISSUE TITLE
Does not limit retries to letsencrypt APIs

### ISSUE THREAD

**Issue by patrakov** [dehydrated-io/dehydrated#596]
Here is an endless loop that retries the checks for pending challenges

https://github.com/lukas2511/dehydrated/blob/master/dehydrated#L803

Today I got it runnung for at least 20 minutes, and the validation is still pending. So, I pressed Ctrl+C.

I think it is a temporary problem on the letsencrypt side, but still, infinite retries mean that there is a risk to get banned.

**Comment by cpu** [comment]
Hi @patrakov 

> I think it is a temporary problem on the letsencrypt side

Can you share the authorization ID that you were stuck polling? I suspect you may have encountered [this Let's Encrypt bug](https://github.com/letsencrypt/boulder/issues/3833) which has been [fixed in Boulder master](https://github.com/letsencrypt/boulder/pull/3844) but not yet deployed (should be ~Thursday).

I agree that its a good idea for Dehydrated to limit retries regardless of the bug fix :-)

**Comment by patrakov** [comment]
I am afraid of posting anything from the "bash -x dehydrated -c -x" log here, because I do not know what is public and what is private.

**Comment by cpu** [comment]
@patrakov If you'd prefer you can share the log in email to `cpu` at `letsencrypt.org`.

**Comment by patrakov** [comment]
I confirm that it was a forced renewal after changing the challenge type from http-01 to dns-01.

**Comment by lukas2511** [comment]
This should be fixed by now as it appears to have been a side-effect of bad JSON parsing.

**Comment by patrakov** [comment]
Well, this particular case was due to bad JSON parsing. However, the issue is about something completely different: retries should be limited no matter what other bugs exist in the code.
