### ISSUE TITLE
Is it possible to use CONTACT_EMAIL only for certain vhosts on a server?

### ISSUE THREAD

**Issue by dave559** [dehydrated-io/dehydrated#734]
Is it possible to use CONTACT_EMAIL only for certain vhosts on the same server?

We have started to use the CONTACT_EMAIL config setting, because, very occasionally, certs fail to renew (usually a problem somewhere at our end, I hasten to add), and this will email us a reminder if a cert doesn't renew timeously.

As part of our website setup processes, we often serve a staging site under a temporary hostname before updating the hostname. Unfortunately, this means that LetsEncrypt now (understandably) emails us when the certs for these transient hostnames are due to expire.

Is there a way in dehydrated to only use the CONTACT_EMAIL setting for specific hostnames, and not for others?

**Comment by lukas2511** [comment]
Since the contact email is for the account and not for the individual certificates there isn't any way to easily configure this. You could in theory hold multiple dehydrated instances, one with contacts one without, but the far far better solution would probably to set up your own certificate monitoring instead of relying on LE to send the notifications.
