### ISSUE TITLE
Incompatibility with freebsd sed?

### ISSUE THREAD

**Issue by lukas2511** [dehydrated-io/dehydrated#756]
There seem to be some issues using dehydrated under FreeBSD atm, need to investigate further...

**Comment by oranenj** [comment]
These issues are likely similar on OpenBSD too. At a cursory glance, things like using `\s` with `grep` and/or `sed` instead of `[[:space:]]` seem to be the primary gnuisms.

I hacked my copy of dehydrated to work by forcing it to use gsed, gawk and ggrep; if making the script POSIX-compliant is too much work, then making it so that it checks for and explicitly uses those commands on non-Linux platforms is a good idea.

**Comment by oranenj** [comment]
I made #761 which works for me; more testing needed though.

**Comment by morganwdavis** [comment]
Could this be why after upgrading from 0.6.5 (which works) to 0.6.6 I'm getting this error:

```
# INFO: Using main config file /usr/local/etc/dehydrated/config
+ Fetching account URL...
ERROR: Problem connecting to server (head for ; curl returned with 3)
ERROR: Problem connecting to server (post for ; curl returned with 3)
```
... and it bails out here without doing anything.

The 0.6.5 version does not start out with "Fetching account URL...", so I'm not even sure what that is trying to do here with 0.6.6.  Have I missed a step in upgrading?  Is there a workaround?

This is running on FreeBSD 12.1-RELEASE-p10 FreeBSD 12.1-RELEASE-p10 GENERIC  amd64

**Comment by lukas2511** [comment]
@morganwdavis could you check if you are still getting errors with the current master branch?

**Comment by morganwdavis** [comment]
Version 0.6.6 confirmed working again on FreeBSD 12.1.

MD5 (dehydrated.sh) = 44d2ff6866cc31dddeef935f099f6690

Thank you, Lukas, and contributors.

**Comment by lukas2511** [comment]
Closing as this should be fixed by now.
