### ISSUE TITLE
Support for new root chain by letsencrypt

### ISSUE THREAD

**Issue by whizzygeeks** [dehydrated-io/dehydrated#843]
Update root chain with new ones specified in https://letsencrypt.org/certificates/

**Comment by lukas2511** [comment]
Dehydrated doesn't have hardcoded chains. It uses the chain as provided by the CA. You can even select alternate chains the CA is offering using the `PREFERRED_CHAIN` config value or the `--preferred-chain` CLI option.

**Comment by grinapo** [comment]
While you're right, Lukas, this probably should be put on the top of readme (both github and else) since it **does bite almost everyone** providing external certs. The full compatible chain (with expired signed X1) fails on any embedded crap (like TVs) as well as _many_ clients using openssl 1.0.xx.
As a community service, instead of letting them find it in closed issues. :-)

Also, solution is spelled out in #842 .

**Comment by whizzygeeks** [comment]
> 
> 
> Dehydrated doesn't have hardcoded chains. It uses the chain as provided by the CA. You can even select alternate chains the CA is offering using the `PREFERRED_CHAIN` config value or the `--preferred-chain` CLI option.

Thanks , readme is not very clear with this
